# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['USE_FRAMEWORKS'] ||= 'static'
ENV['RCT_NEW_ARCH_ENABLED'] ||= '1'

$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true

platform :ios, min_ios_version_supported
prepare_react_native_project!

project 'TaskManagementApp', {
  'Debug' => :debug,
  'Release' => :release,
  'Debug-Staging' => :debug,
  'Release-Staging' => :release,
  'Debug-Production' => :debug,
  'Release-Production' => :release,
}

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TaskManagementApp' do
  config = use_native_modules!


  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |pod_target|
      next unless pod_target.name == 'react-native-config'
      pod_target.build_configurations.each do |pod_config|
        defs = pod_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = [defs] if defs.is_a?(String)
        defs << 'RCT_NEW_ARCH_ENABLED=1' unless defs.include?('RCT_NEW_ARCH_ENABLED=1')
        pod_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end
  end
end
